import type { FormField } from "@/components/dynamic-form/form-builder"

// Personal Data Fields
export const personalDataFields: FormField[] = [
  {
    name: "url_foto",
    label: "Foto Profil",
    type: "file",
    description: "Unggah foto profil Anda",
  },
  {
    name: "nama",
    label: "Nama Lengkap",
    type: "text",
    placeholder: "Masukkan nama lengkap",
    required: true,
  },
  {
    name: "front_degree",
    label: "Gelar Depan",
    type: "text",
    placeholder: "Contoh: Dr., Prof.",
  },
  {
    name: "back_degree",
    label: "Gelar Belakang",
    type: "text",
    placeholder: "Contoh: S.Pd., M.Pd., Ph.D.",
  },
  {
    name: "tempat_lahir",
    label: "Tempat Lahir",
    type: "text",
    placeholder: "Masukkan tempat lahir",
  },
  {
    name: "tanggal_lahir",
    label: "Tanggal Lahir",
    type: "date",
  },
  {
    name: "jenis_kelamin",
    label: "Jenis Kelamin",
    type: "select",
    placeholder: "Pilih jenis kelamin",
    options: [
      { label: "Laki-laki", value: "Laki-laki" },
      { label: "Perempuan", value: "Perempuan" },
    ],
  },
  {
    name: "alamat",
    label: "Alamat",
    type: "textarea",
    placeholder: "Masukkan alamat lengkap",
  },
  {
    name: "telepon",
    label: "Nomor Telepon",
    type: "text",
    placeholder: "Masukkan nomor telepon",
    required: true,
  },
  {
    name: "nomor_pegawai",
    label: "NIP/NIDN",
    type: "text",
    placeholder: "Masukkan NIP/NIDN",
    required: true,
  },
  {
    name: "jabatan",
    label: "Jabatan Akademik",
    type: "select",
    placeholder: "Pilih jabatan akademik",
    required: true,
    options: [
      { label: "Asisten Ahli", value: "Asisten Ahli" },
      { label: "Lektor", value: "Lektor" },
      { label: "Lektor Kepala", value: "Lektor Kepala" },
      { label: "Profesor", value: "Profesor" },
      { label: "Tenaga Pengajar", value: "Tenaga Pengajar" },
    ],
  },
  {
    name: "status_kepegawaian",
    label: "Status Kepegawaian",
    type: "select",
    placeholder: "Pilih status kepegawaian",
    options: [
      { label: "PNS", value: "PNS" },
      { label: "PPPK", value: "PPPK" },
      { label: "Tetap", value: "Tetap" },
      { label: "Tidak Tetap", value: "Tidak Tetap" },
      { label: "Kontrak", value: "Kontrak" },
    ],
  },
  {
    name: "spesialisasi",
    label: "Bidang Keahlian",
    type: "text",
    placeholder: "Masukkan bidang keahlian",
  },
  {
    name: "gelar_tertinggi",
    label: "Gelar Tertinggi",
    type: "select",
    placeholder: "Pilih gelar tertinggi",
    options: [
      { label: "S1/Sarjana", value: "S1" },
      { label: "S2/Magister", value: "S2" },
      { label: "S3/Doktor", value: "S3" },
    ],
  },
  {
    name: "institusi",
    label: "Institusi Pendidikan Terakhir",
    type: "text",
    placeholder: "Masukkan institusi pendidikan terakhir",
  },
  {
    name: "tahun_lulus",
    label: "Tahun Lulus",
    type: "number",
    placeholder: "Masukkan tahun lulus pendidikan terakhir",
  },
  {
    name: "biografi",
    label: "Biografi",
    type: "textarea",
    placeholder: "Tuliskan biografi singkat",
  },
]

// Research Fields
export const researchFields: FormField[] = [
  {
    name: "judul",
    label: "Judul Penelitian",
    type: "text",
    placeholder: "Masukkan judul penelitian",
    required: true,
  },
  {
    name: "latar_belakang",
    label: "Latar Belakang",
    type: "textarea",
    placeholder: "Jelaskan latar belakang penelitian",
    required: true,
  },
  {
    name: "peran",
    label: "Peran",
    type: "select",
    placeholder: "Pilih peran Anda dalam penelitian",
    options: [
      { label: "Ketua", value: "Ketua" },
      { label: "Anggota", value: "Anggota" },
      { label: "Kontributor", value: "Kontributor" },
    ],
  },
  {
    name: "tanggal_mulai",
    label: "Tanggal Mulai",
    type: "date",
    required: true,
  },
  {
    name: "tanggal_selesai",
    label: "Tanggal Selesai",
    type: "date",
  },
  {
    name: "sedang_berjalan",
    label: "Sedang Berjalan",
    type: "checkbox",
  },
  {
    name: "sumber_dana",
    label: "Sumber Dana",
    type: "text",
    placeholder: "Masukkan sumber dana",
  },
  {
    name: "kategori_sumber_dana",
    label: "Kategori Sumber Dana",
    type: "select",
    placeholder: "Pilih kategori sumber dana",
    options: [
      { label: "Mandiri", value: "Mandiri" },
      { label: "Internal", value: "Internal" },
      { label: "Pemerintah", value: "Pemerintah" },
      { label: "Swasta", value: "Swasta" },
      { label: "Luar Negeri", value: "Luar Negeri" },
      { label: "Lainnya", value: "Lainnya" },
    ],
  },
  {
    name: "jumlah_dana",
    label: "Jumlah Dana",
    type: "text",
    placeholder: "Masukkan jumlah dana",
  },
  {
    name: "melibatkan_mahasiswa",
    label: "Melibatkan Mahasiswa",
    type: "checkbox",
  },
  {
    name: "jumlah_mahasiswa",
    label: "Jumlah Mahasiswa",
    type: "text",
    placeholder: "Masukkan jumlah mahasiswa yang terlibat",
  },
  {
    name: "status_publikasi",
    label: "Status Publikasi",
    type: "select",
    placeholder: "Pilih status publikasi",
    options: [
      { label: "Belum Dipublikasikan", value: "Belum Dipublikasikan" },
      { label: "Dalam Proses", value: "Dalam Proses" },
      { label: "Sudah Dipublikasikan", value: "Sudah Dipublikasikan" },
    ],
  },
  {
    name: "nama_jurnal",
    label: "Nama Jurnal",
    type: "text",
    placeholder: "Masukkan nama jurnal (jika dipublikasikan)",
  },
  {
    name: "fokus",
    label: "Fokus Penelitian",
    type: "text",
    placeholder: "Masukkan fokus penelitian",
  },
  {
    name: "skema",
    label: "Skema Penelitian",
    type: "text",
    placeholder: "Masukkan skema penelitian",
  },
  {
    name: "lokasi",
    label: "Lokasi Penelitian",
    type: "text",
    placeholder: "Masukkan lokasi penelitian",
  },
  {
    name: "status_penetapan",
    label: "Status Penetapan",
    type: "select",
    placeholder: "Pilih status penetapan",
    options: [
      { label: "Diterima", value: "Diterima" },
      { label: "Ditolak", value: "Ditolak" },
      { label: "Dalam Proses", value: "Dalam Proses" },
      { label: "Revisi", value: "Revisi" },
    ],
  },
  {
    name: "ketua_peneliti",
    label: "Ketua Peneliti",
    type: "text",
    placeholder: "Masukkan nama ketua peneliti",
  },
  {
    name: "nidn_ketua",
    label: "NIDN Ketua",
    type: "text",
    placeholder: "Masukkan NIDN ketua peneliti",
  },
  {
    name: "tahun_pelaksanaan",
    label: "Tahun Pelaksanaan",
    type: "number",
    placeholder: "Masukkan tahun pelaksanaan",
  },
  {
    name: "tahun_pengajuan_pertama",
    label: "Tahun Pengajuan Pertama",
    type: "number",
    placeholder: "Masukkan tahun pengajuan pertama",
  },
  {
    name: "program_hibah",
    label: "Program Hibah",
    type: "text",
    placeholder: "Masukkan program hibah",
  },
  {
    name: "negara_sumber_dana",
    label: "Negara Sumber Dana",
    type: "text",
    placeholder: "Masukkan negara sumber dana (jika luar negeri)",
  },
]

// Community Service Fields
export const communityServiceFields: FormField[] = [
  {
    name: "judul",
    label: "Judul Pengabdian",
    type: "text",
    placeholder: "Masukkan judul pengabdian masyarakat",
    required: true,
  },
  {
    name: "deskripsi",
    label: "Deskripsi",
    type: "textarea",
    placeholder: "Jelaskan deskripsi pengabdian masyarakat",
    required: true,
  },
  {
    name: "peran",
    label: "Peran",
    type: "select",
    placeholder: "Pilih peran Anda dalam pengabdian",
    options: [
      { label: "Ketua", value: "Ketua" },
      { label: "Anggota", value: "Anggota" },
      { label: "Kontributor", value: "Kontributor" },
    ],
  },
  {
    name: "tanggal_mulai",
    label: "Tanggal Mulai",
    type: "date",
    required: true,
  },
  {
    name: "tanggal_selesai",
    label: "Tanggal Selesai",
    type: "date",
  },
  {
    name: "sedang_berjalan",
    label: "Sedang Berjalan",
    type: "checkbox",
  },
  {
    name: "lokasi",
    label: "Lokasi",
    type: "text",
    placeholder: "Masukkan lokasi pengabdian masyarakat",
    required: true,
  },
  {
    name: "mitra",
    label: "Mitra",
    type: "text",
    placeholder: "Masukkan mitra pengabdian masyarakat",
  },
  {
    name: "penerima_manfaat",
    label: "Penerima Manfaat",
    type: "text",
    placeholder: "Masukkan penerima manfaat",
  },
  {
    name: "sumber_dana",
    label: "Sumber Dana",
    type: "text",
    placeholder: "Masukkan sumber dana",
  },
  {
    name: "jumlah_dana",
    label: "Jumlah Dana",
    type: "text",
    placeholder: "Masukkan jumlah dana",
  },
  {
    name: "hasil",
    label: "Hasil Pengabdian",
    type: "textarea",
    placeholder: "Jelaskan hasil pengabdian masyarakat",
  },
]

// Publication Fields
export const publicationFields: FormField[] = [
  {
    name: "judul",
    label: "Judul Publikasi",
    type: "text",
    placeholder: "Masukkan judul publikasi",
    required: true,
  },
  {
    name: "penulis",
    label: "Penulis",
    type: "text",
    placeholder: "Masukkan nama penulis (pisahkan dengan koma)",
    required: true,
  },
  {
    name: "abstrak",
    label: "Abstrak",
    type: "textarea",
    placeholder: "Masukkan abstrak publikasi",
  },
  {
    name: "jenis_publikasi",
    label: "Jenis Publikasi",
    type: "select",
    placeholder: "Pilih jenis publikasi",
    required: true,
    options: [
      { label: "Artikel Jurnal", value: "Artikel Jurnal" },
      { label: "Prosiding", value: "Prosiding" },
      { label: "Buku", value: "Buku" },
      { label: "Book Chapter", value: "Book Chapter" },
      { label: "Lainnya", value: "Lainnya" },
    ],
  },
  {
    name: "tahun",
    label: "Tahun Publikasi",
    type: "number",
    placeholder: "Masukkan tahun publikasi",
    required: true,
  },
  {
    name: "penerbit",
    label: "Penerbit",
    type: "text",
    placeholder: "Masukkan nama penerbit",
  },
  {
    name: "nama_jurnal",
    label: "Nama Jurnal/Konferensi",
    type: "text",
    placeholder: "Masukkan nama jurnal atau konferensi",
  },
  {
    name: "volume",
    label: "Volume",
    type: "text",
    placeholder: "Masukkan volume publikasi",
  },
  {
    name: "edisi",
    label: "Edisi/Issue",
    type: "text",
    placeholder: "Masukkan edisi atau issue",
  },
  {
    name: "halaman",
    label: "Halaman",
    type: "text",
    placeholder: "Masukkan halaman (mis: 123-135)",
  },
  {
    name: "doi",
    label: "DOI",
    type: "text",
    placeholder: "Masukkan DOI publikasi",
  },
  {
    name: "url",
    label: "URL",
    type: "text",
    placeholder: "Masukkan URL publikasi",
  },
  {
    name: "kata_kunci",
    label: "Kata Kunci",
    type: "text",
    placeholder: "Masukkan kata kunci (pisahkan dengan koma)",
  },
  {
    name: "terindeks",
    label: "Terindeks Pada",
    type: "text",
    placeholder: "Masukkan indeks publikasi (Scopus, WoS, dll)",
  },
  {
    name: "faktor_dampak",
    label: "Faktor Dampak",
    type: "text",
    placeholder: "Masukkan faktor dampak jika ada",
  },
  {
    name: "jumlah_sitasi",
    label: "Jumlah Sitasi",
    type: "number",
    placeholder: "Masukkan jumlah sitasi",
  },
]

// Intellectual Property Fields
export const intellectualPropertyFields: FormField[] = [
  {
    name: "judul",
    label: "Judul HKI",
    type: "text",
    placeholder: "Masukkan judul hak kekayaan intelektual",
    required: true,
  },
  {
    name: "jenis",
    label: "Jenis HKI",
    type: "select",
    placeholder: "Pilih jenis HKI",
    required: true,
    options: [
      { label: "Paten", value: "Paten" },
      { label: "Hak Cipta", value: "Hak Cipta" },
      { label: "Merek Dagang", value: "Merek Dagang" },
      { label: "Desain Industri", value: "Desain Industri" },
      { label: "Lainnya", value: "Lainnya" },
    ],
  },
  {
    name: "nomor_pendaftaran",
    label: "Nomor Pendaftaran",
    type: "text",
    placeholder: "Masukkan nomor pendaftaran",
  },
  {
    name: "tanggal_pendaftaran",
    label: "Tanggal Pendaftaran",
    type: "date",
  },
  {
    name: "tanggal_pemberian",
    label: "Tanggal Pemberian",
    type: "date",
  },
  {
    name: "status",
    label: "Status",
    type: "select",
    placeholder: "Pilih status HKI",
    options: [
      { label: "Terdaftar", value: "Terdaftar" },
      { label: "Granted", value: "Granted" },
      { label: "Dalam Proses", value: "Dalam Proses" },
      { label: "Ditolak", value: "Ditolak" },
    ],
  },
  {
    name: "penemu",
    label: "Penemu/Pencipta",
    type: "text",
    placeholder: "Masukkan nama penemu/pencipta (pisahkan dengan koma)",
    required: true,
  },
  {
    name: "pemilik",
    label: "Pemilik HKI",
    type: "text",
    placeholder: "Masukkan nama pemilik HKI",
  },
  {
    name: "deskripsi",
    label: "Deskripsi",
    type: "textarea",
    placeholder: "Jelaskan deskripsi HKI",
  },
  {
    name: "negara",
    label: "Negara",
    type: "text",
    placeholder: "Masukkan negara tempat pendaftaran",
  },
  {
    name: "tanggal_berakhir",
    label: "Tanggal Berakhir",
    type: "date",
  },
]

// Recognition Fields
export const recognitionFields: FormField[] = [
  {
    name: "judul",
    label: "Judul Penghargaan",
    type: "text",
    placeholder: "Masukkan judul penghargaan/rekognisi",
    required: true,
  },
  {
    name: "pemberi",
    label: "Pemberi Penghargaan",
    type: "text",
    placeholder: "Masukkan institusi/lembaga pemberi penghargaan",
    required: true,
  },
  {
    name: "deskripsi",
    label: "Deskripsi",
    type: "textarea",
    placeholder: "Jelaskan deskripsi penghargaan",
  },
  {
    name: "tanggal",
    label: "Tanggal Penghargaan",
    type: "date",
    required: true,
  },
  {
    name: "tingkat",
    label: "Tingkat Penghargaan",
    type: "select",
    placeholder: "Pilih tingkat penghargaan",
    options: [
      { label: "Internasional", value: "Internasional" },
      { label: "Nasional", value: "Nasional" },
      { label: "Regional", value: "Regional" },
      { label: "Institusional", value: "Institusional" },
    ],
  },
  {
    name: "kategori",
    label: "Kategori Penghargaan",
    type: "text",
    placeholder: "Masukkan kategori penghargaan",
  },
]
