export * from './dashboard-client-wrapper';
export * from './dashboard-analytics';
export * from './recent-activities';
export * from './personal-data-tab';
export * from './research-tab';
export * from './community-service-tab';
export * from './publications-tab';
export * from './intellectual-property-tab';
export * from './recognition-tab'; 
